pipeline {
  agent any

  environment {
    PROJECT_ID = "pavan-477919"    // 👈 CHANGE
    REGISTRY   = "docker.io/pavanyennu"
    TAG        = "${BUILD_NUMBER}"
  }

  stages {

   stage('Build') {
  steps {
    sh '''
    cd docker/backend && mvn clean package
    cd ../frontend && mvn clean package
    cd ../payments && mvn clean package
    '''
  }
}
stage('Fetch Sonar Token from GSM') {
  steps {
    script {
      env.SONAR_TOKEN = sh(
        script: '''
        gcloud secrets versions access latest \
          --secret=sonar-token \
          --project=pavan-477919
        ''',
        returnStdout: true
      ).trim()
    }
  }
}
stage('SonarQube Scan') {
  steps {
    sh '''
    mvn sonar:sonar \
      -Dsonar.login=$SONAR_TOKEN \
      -Dsonar.host.url=http://sonarqube.sonarqube.svc.cluster.local:9000
    '''
  }
}

    stage('Docker Build') {
  steps {
    sh '''
    docker build -t ${REGISTRY}/backend:${TAG} docker/backend
    docker build -t ${REGISTRY}/frontend:${TAG} docker/frontend
    docker build -t ${REGISTRY}/payments:${TAG} docker/payments
    '''
  }
}


    stage('Push Images') {
      steps {
        sh '''
        docker push ${REGISTRY}/frontend:${TAG}
        docker push ${REGISTRY}/backend:${TAG}
        docker push ${REGISTRY}/payments:${TAG}
        '''
      }
    }

    stage('Helm Deploy') {
      steps {
        sh '''
        helm upgrade --install microservices charts/microservices \
          --set image.tag=${TAG}
        '''
      }
    }
  }
}
